[build]
target = "index.html"
dist = "dist"
public_url = "/"
release = true
filehash = true
rustup = "/Users/kyosukeishizu/.cargo/bin/rustup"
cargo = "/Users/kyosukeishizu/.cargo/bin/cargo"

[tools]
wasm-opt = false

[watch]
watch = ["src", "index.html"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8081
open = false
