[build]
target = "index.html"
dist = "dist"
public_url = "/berry-editor/"
release = true
filehash = false

[tools]
wasm-opt = false

[watch]
watch = ["src", "index.html"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8081
open = false
